### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by mojoaxel** [cadus/remo2hbo_oktopus_frontend#2]
The frontend is missing license information. This [must be added](https://help.github.com/en/articles/adding-a-license-to-a-repository) to be able to contribute.
- [LICENSE.md file]()
- update of the license in [package.json#L18](https://github.com/cadus/remo2hbo_oktopus_frontend/blob/master/package.json#L18)

**Comment by mojoaxel** [comment]
@andreakreichgauer I would recommend AGPL-3.0 like in the backend.

**Comment by sabinammm** [comment]
> @andreakreichgauer I would recommend AGPL-3.0 like in the backend.

Thanks for the recommendation. I've added the licensing info.
